project_id = "Projet_coiffeur"

# ✅ Désactivation complète des services locaux (Cloud Only)
[api]
enabled = false

[db]
enabled = false

[db.pooler]
enabled = false

[db.seed]
enabled = false

[realtime]
enabled = false

[studio]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false

[auth]
enabled = false

# ✅ Activer uniquement la fonction Edge `send-email-v2`
[functions.send-email-v2]
enabled = true
import_map = "./functions/send-email-v2/deno.json"
verify_jwt = true

# ✅ Désactivation complète du mode Edge Runtime local
[edge_runtime]
enabled = false

[analytics]
enabled = false